// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiKP5vyunNwXtXwL9FRDqi2F3serJrduo',
    appId: '1:478260383391:web:a430a445b7b2a40f275caa',
    messagingSenderId: '478260383391',
    projectId: 'evently-app-780dd',
    authDomain: 'evently-app-780dd.firebaseapp.com',
    storageBucket: 'evently-app-780dd.firebasestorage.app',
    measurementId: 'G-5ZXM8EXKFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH_wZ1r0SX966tyRpdu9F-w3INVj7qECo',
    appId: '1:478260383391:android:f2fbcf3f4997d724275caa',
    messagingSenderId: '478260383391',
    projectId: 'evently-app-780dd',
    storageBucket: 'evently-app-780dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd-4_FiJ9XTuSB3gqZ3BiqvRiPNLcVhWo',
    appId: '1:478260383391:ios:ce677bd1dcb6bf63275caa',
    messagingSenderId: '478260383391',
    projectId: 'evently-app-780dd',
    storageBucket: 'evently-app-780dd.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd-4_FiJ9XTuSB3gqZ3BiqvRiPNLcVhWo',
    appId: '1:478260383391:ios:ce677bd1dcb6bf63275caa',
    messagingSenderId: '478260383391',
    projectId: 'evently-app-780dd',
    storageBucket: 'evently-app-780dd.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiKP5vyunNwXtXwL9FRDqi2F3serJrduo',
    appId: '1:478260383391:web:e8a152cfd4b8a766275caa',
    messagingSenderId: '478260383391',
    projectId: 'evently-app-780dd',
    authDomain: 'evently-app-780dd.firebaseapp.com',
    storageBucket: 'evently-app-780dd.firebasestorage.app',
    measurementId: 'G-70PDJ71SL8',
  );
}
